name: acrilc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.12
  gap: ^3.0.1
  go_router: ^14.8.1
  http: ^1.3.0
  http_mock_adapter: ^0.6.1
  image_picker: ^1.1.2
  insta_image_viewer: ^1.0.4
  intl: ^0.20.2
  logger: ^2.5.0
  mime: ^2.0.0
  mockito: ^5.4.5
  photo_view: ^0.15.0
  provider: ^6.1.3
  rename_app: ^1.6.2
  share_plus: ^10.1.4
  shared_preferences: ^2.5.2
  socket_io_client: ^3.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.24.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - prod.env

fonts:
  family: Poppins
  fonts:
    - asset: assets/fonts/Poppins-Regular.ttf
